name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{github.workspace}}
    steps:
      - env:
          RUNNER_OS: ${{runner.os}}
      - run: echo "${WORKSPACE} ${RUNNER_OS}"
