name: Contexts
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      WORKSPACE: ${{github.workspace}}
    steps:
      - run: echo "${WORKSPACE} ${RUNNER_OS}"
        env:
          RUNNER_OS: ${{ runner.os }}"
