name: Functions
run-name: Run by @${{ github.actor }}
on: push
jobs:
 skip-or-run-2:
    if: ${{ github.actor == 'xxx' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
 compare:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          CONTAINS_FUNC: ${{ contains('Hello', 'ell') }}
          STARS_WITH_FUNC: ${{ startsWith('Hello', 'He') }}
          ENDS_WITH_FUNC: ${{ endsWith('Hello', 'lo') }}
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'world') }}
          JOIN_FUNC: ${{ join(github.event.*.html_url, ',') }}
  hash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "${HASH}"
        env:
          HASH: ${{ hashFiles('.github/workflows/*.yml') }}
  skip-or-run-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}
  fail:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - run: echo "FAILED!!"
        if: ${{ failure() }}
  print:
    name: Supre Useful Job
    runs-on: ubuntu-latest
    steps:
      - name: Amazing Script
        run: echo "Goog Job"
